# CONFIG for Jekyll

# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            Docs
tagline:
url:              "http://ashenheim.github.com/docs"
baseurl:          "/docs"
author:
- name:           Patrick Gurr
- url:            https://twitter.com/ashenheim
- email:          patrick@gmail.com


# Build
markdown: redcarpet
highlighter: pygments
exclude: [
    'node_modules',
    'bower_components',
    'bower.json',
    'gulpfile.js',
    'package.json',
    'README.md',
    'gulp'
]

collections:
  docs:
    output: true
    url: /docs/:title
    layout: default