# CONFIG for Jekyll

# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            Docs
tagline:
url:              "http://docs.smashingpat.com/"
baseurl:          ""
author:
- name:           Patrick Gurr
- url:            https://twitter.com/ashenheim
- email:          patrick@gmail.com


# Build
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]

highlighter: pygments
exclude: [
    'node_modules',
    'bower_components',
    'bower.json',
    'gulpfile.js',
    'package.json',
    'README.md',
    'gulp'
]

collections:
  docs:
    output: true
    permalink: /docs/:title/
